version: "3.7"

services: 
  swarm-server:
    build: 
      context: .
      dockerfile: demo.Dockerfile
    #container_name: swarm-server
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
      # mode: global
      # placement:
      #   constraints:
      #     - node.labels.service == server
    ports:
      - "8800:8800"
    expose:
      - "8800"
